install:
  - sudo apt-get -y install jq
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - sudo ./aws/install
  - git clone https://github.com/tfutils/tfenv.git ~/.tfenv
  - sudo ln -s ~/.tfenv/bin/* /usr/local/bin
  - tfenv install

script:
  - terraform init
  - tests/tests.sh
